### ISSUE TITLE
[BUG] missing translation breaks gantt

### ISSUE THREAD

**Issue by BlueTeck** [BlueTeck/kanboard_plugin_gantt#7]
Missing languages in

`const month_names = {`
https://github.com/BlueTeck/kanboard_plugin_gantt/blob/master/Assets/frappe-gantt.min.js 

are breaking the diagram, if other language is passed in 

`language: jQuery("html").attr("lang"),`
https://github.com/BlueTeck/kanboard_plugin_gantt/blob/master/Assets/gantt.js#L55

**Comment by Capataloutchoupika** [comment]
Patch applied in ed78f3b82f9bea706e66868cc0d808242998f6f3

https://github.com/BlueTeck/kanboard_plugin_gantt/blob/7c06dd35f00f669ceacb3b51eb602cca57761f6d/Assets/frappe-gantt.min.js#L1115
